#!/usr/bin/env python3
"""
Agent / 小白 统一入口（推荐）
============================
其他人的 Agent 只需：

  git clone https://github.com/fredombobo/a-share-accumulation-breakout.git
  cd a-share-accumulation-breakout
  python bootstrap.py --token <TUSHARE_TOKEN>

完成：写 .env → 装依赖 → 同步行情 → 启动 Web → 打印访问地址。

用户只需提供 Tushare Token，其余全自动。
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
import webbrowser
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV_PATH = ROOT / ".env"
ENV_EXAMPLE = ROOT / ".env.example"
REQ = ROOT / "requirements.txt"
RUNTIME = ROOT / "runtime"
DB = RUNTIME / "stock_data.db"
DIST_INDEX = ROOT / "web" / "frontend" / "dist" / "index.html"
BACKEND = ROOT / "web" / "backend_app.py"
OPEN_URL = "http://127.0.0.1:8000/"
HEALTH_URL = "http://127.0.0.1:8000/api/health"

PLACEHOLDER_TOKENS = frozenset({"", "your_token_here", "changeme", "xxx", "TOKEN", "<TUSHARE_TOKEN>"})


def _clear_proxy() -> None:
    os.environ.pop("PYTHONPATH", None)
    for k in (
        "HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY",
        "http_proxy", "https_proxy", "all_proxy",
    ):
        os.environ.pop(k, None)


def _log(msg: str) -> None:
    print(msg, flush=True)


def _find_python() -> str:
    # 优先当前解释器（Agent 通常已选定）
    if sys.executable:
        return sys.executable
    for p in (
        Path(r"C:\Python314\python.exe"),
        Path(r"C:\Python313\python.exe"),
        Path(r"C:\Python312\python.exe"),
    ):
        if p.is_file():
            return str(p)
    return "python"


def _normalize_token(raw: str | None) -> str:
    t = (raw or "").strip().strip('"').strip("'")
    if t.lower().startswith("tushare_token="):
        t = t.split("=", 1)[1].strip()
    return t


def _token_ok(token: str) -> bool:
    return bool(token) and token not in PLACEHOLDER_TOKENS and len(token) >= 8


def _read_token_from_env_file() -> str:
    if not ENV_PATH.is_file():
        return ""
    try:
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if s.startswith("TUSHARE_TOKEN=") and not s.startswith("#"):
                return _normalize_token(s.split("=", 1)[1])
    except OSError:
        return ""
    return ""


def resolve_token(cli_token: str | None) -> str:
    """优先级：CLI --token > 环境变量 > .env 文件。"""
    for cand in (
        _normalize_token(cli_token),
        _normalize_token(os.environ.get("TUSHARE_TOKEN")),
        _read_token_from_env_file(),
    ):
        if _token_ok(cand):
            return cand
    return ""


def write_env(token: str) -> None:
    """写入/更新 .env（不打印 token）。"""
    lines: list[str] = []
    if ENV_PATH.is_file():
        lines = ENV_PATH.read_text(encoding="utf-8").splitlines()
    elif ENV_EXAMPLE.is_file():
        lines = ENV_EXAMPLE.read_text(encoding="utf-8").splitlines()
    else:
        lines = [
            "# auto-generated by bootstrap.py",
            "TUSHARE_TOKEN=",
            "TUSHARE_HTTP_URL=http://a.sszhixia.cn/",
        ]

    out: list[str] = []
    replaced = False
    for line in lines:
        if line.strip().startswith("TUSHARE_TOKEN="):
            out.append(f"TUSHARE_TOKEN={token}")
            replaced = True
        else:
            out.append(line)
    if not replaced:
        out.insert(0, f"TUSHARE_TOKEN={token}")

    # 确保有 HTTP URL
    if not any(x.strip().startswith("TUSHARE_HTTP_URL=") for x in out):
        out.append("TUSHARE_HTTP_URL=http://a.sszhixia.cn/")

    ENV_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")
    os.environ["TUSHARE_TOKEN"] = token
    _log(f"[ok] 已写入 {ENV_PATH.name}（Token 已保存，不会回显）")


def load_dotenv() -> None:
    if not ENV_PATH.is_file():
        return
    try:
        for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
            s = line.strip()
            if not s or s.startswith("#") or "=" not in s:
                continue
            k, v = s.split("=", 1)
            k, v = k.strip(), v.strip().strip('"').strip("'")
            if k:
                os.environ[k] = v
    except OSError:
        pass


def pip_install(py: str) -> None:
    _log("[1/4] 安装 Python 依赖…")
    cmd = [py, "-m", "pip", "install", "-r", str(REQ), "-q"]
    r = subprocess.run(cmd, cwd=str(ROOT))
    if r.returncode != 0:
        # 再试一次非 quiet，方便 Agent 排错
        r2 = subprocess.run([py, "-m", "pip", "install", "-r", str(REQ)], cwd=str(ROOT))
        if r2.returncode != 0:
            raise SystemExit(
                "依赖安装失败。请确认 Python 3.11+ 且网络可用。\n"
                f"手动: {py} -m pip install -r requirements.txt"
            )
    _log("[ok] 依赖就绪")


def sync_market(py: str, days: int | None) -> None:
    first = (not DB.is_file()) or DB.stat().st_size < 1_000_000
    if days is None:
        days = 200 if first else 30
    if first:
        _log(f"[2/4] 首次建库同步（约 30～90 分钟，days={days}）…")
    else:
        _log(f"[2/4] 增量同步行情（约 2～10 分钟，days={days}）…")
    r = subprocess.run(
        [py, str(ROOT / "sync_daily.py"), "--days", str(days)],
        cwd=str(ROOT),
        env=os.environ.copy(),
    )
    if r.returncode != 0:
        _log("[warn] 同步未完全成功，仍会启动界面（可用旧数据或稍后重试）")
    else:
        _log("[ok] 行情同步完成")


def health_ok(timeout: float = 2.0) -> bool:
    import urllib.error
    import urllib.request

    try:
        with urllib.request.urlopen(HEALTH_URL, timeout=timeout) as r:  # noqa: S310
            return r.status == 200
    except (urllib.error.URLError, TimeoutError, OSError):
        return False


def wait_health(timeout: float = 60.0) -> bool:
    t0 = time.time()
    while time.time() - t0 < timeout:
        if health_ok():
            return True
        time.sleep(0.5)
    return False


def _port_in_use(port: int = 8000) -> bool:
    """检查端口是否已被占用（存在监听者）。"""
    import socket
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.settimeout(0.5)
        try:
            return s.connect_ex(("127.0.0.1", port)) == 0
        except OSError:
            return False


def start_server(py: str, foreground: bool) -> subprocess.Popen | None:
    if not DIST_INDEX.is_file():
        _log("[warn] 未找到 web/frontend/dist，界面可能不完整（API 仍可用）")
    if health_ok(timeout=1.0):
        _log("[3/4] 服务已在运行")
        return None
    if _port_in_use(8000):
        _log("[3/4] 端口 8000 已被占用但服务不响应（疑似残留进程）")
        _log("       请先运行 停止.bat（或 stop_ui.ps1）清理残留进程后再启动")
        return None

    RUNTIME.mkdir(parents=True, exist_ok=True)
    _log("[3/4] 启动 Web 服务 :8000 …")

    if foreground:
        # 阻塞在前台，适合 Agent 托管长进程
        os.chdir(ROOT / "web")
        os.execv(py, [py, str(BACKEND)])  # noqa: S606

    out_log = open(RUNTIME / "bootstrap.out.log", "w", encoding="utf-8")  # noqa: SIM115
    err_log = open(RUNTIME / "bootstrap.err.log", "w", encoding="utf-8")  # noqa: SIM115
    proc = subprocess.Popen(
        [py, str(BACKEND)],
        cwd=str(ROOT / "web"),
        stdout=out_log,
        stderr=err_log,
        env=os.environ.copy(),
    )
    (RUNTIME / "backend.pid").write_text(str(proc.pid), encoding="ascii")
    return proc


def print_success() -> None:
    _log("")
    _log("=" * 52)
    _log("  启动成功")
    _log(f"  打开界面: {OPEN_URL}")
    _log("  用户操作: 点「扫描」→ 等 5～15 分钟 → 看 A 池")
    _log("  停止服务: python -c \"import pathlib; p=pathlib.Path('runtime/backend.pid');")
    _log("            import os,signal; os.kill(int(p.read_text()), signal.SIGTERM)\"")
    _log("            或双击 停止.bat / 运行 stop_ui.ps1")
    _log("=" * 52)
    _log("")
    # Agent 机器可读摘要
    print("BOOTSTRAP_OK url=" + OPEN_URL, flush=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="一键：配置 Token + 装依赖 + 同步 + 启动（Agent/小白通用）",
    )
    parser.add_argument(
        "--token",
        default=None,
        help="Tushare API Token（也可设环境变量 TUSHARE_TOKEN）",
    )
    parser.add_argument(
        "--yes", "-y",
        action="store_true",
        help="非交互（Agent 模式必须加）",
    )
    parser.add_argument("--skip-sync", action="store_true", help="跳过行情同步")
    parser.add_argument("--sync-days", type=int, default=None, help="同步回看天数")
    parser.add_argument("--no-browser", action="store_true", help="不自动打开浏览器")
    parser.add_argument(
        "--foreground",
        action="store_true",
        help="前台阻塞运行服务（适合 Agent 常驻进程）",
    )
    parser.add_argument(
        "--install-only",
        action="store_true",
        help="只写 Token + 装依赖，不启动",
    )
    args = parser.parse_args(argv)

    _clear_proxy()
    _log("=" * 52)
    _log(" accumulation-breakout bootstrap")
    _log(" repo root: " + str(ROOT))
    _log("=" * 52)

    token = resolve_token(args.token)
    if not _token_ok(token):
        if args.yes or not sys.stdin.isatty():
            _log("ERROR: 缺少有效 Tushare Token。")
            _log("用法: python bootstrap.py --token <YOUR_TOKEN> --yes")
            _log("  或: set TUSHARE_TOKEN=... && python bootstrap.py --yes")
            return 2
        try:
            entered = input("请粘贴 Tushare Token 后回车: ").strip()
        except EOFError:
            entered = ""
        token = _normalize_token(entered)
        if not _token_ok(token):
            _log("ERROR: Token 无效。请到 https://tushare.pro 注册获取。")
            return 2

    write_env(token)
    load_dotenv()

    py = _find_python()
    _log(f"[env] python = {py}")
    pip_install(py)
    load_dotenv()

    if args.install_only:
        _log("[ok] install-only 完成。启动请运行: python bootstrap.py --yes --skip-sync")
        print("BOOTSTRAP_OK install_only=1", flush=True)
        return 0

    if not args.skip_sync:
        try:
            sync_market(py, args.sync_days)
        except KeyboardInterrupt:
            _log("[warn] 同步中断，继续启动…")

    if args.foreground:
        print_success()
        if not args.no_browser:
            try:
                webbrowser.open(OPEN_URL)
            except Exception:  # noqa: BLE001
                pass
        start_server(py, foreground=True)
        return 0  # exec 不会到这里

    start_server(py, foreground=False)
    if not wait_health(60):
        err = RUNTIME / "bootstrap.err.log"
        _log("ERROR: 服务未在 60s 内就绪。")
        if err.is_file():
            _log("--- bootstrap.err.log (tail) ---")
            try:
                _log("\n".join(err.read_text(encoding="utf-8", errors="replace").splitlines()[-30:]))
            except OSError:
                pass
        return 1

    if not args.no_browser:
        try:
            webbrowser.open(OPEN_URL)
        except Exception:  # noqa: BLE001
            pass

    print_success()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
