"""Deterministic portfolio accounting for trusted Breakout research.

Candidate trades are generated by the frozen signal/exit engine.  This module
adds the account layer that the legacy trade-sequence summary lacked: shared
cash, overlapping positions, portfolio limits, exact integer fees and daily
mark-to-market equity.  It never changes a signal or chooses an exit parameter.
"""

from __future__ import annotations

import hashlib
import json
from collections import Counter, defaultdict
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from ab_screener.domain.execution.fees import FeeParams
from ab_screener.domain.execution.fill_model import FillRequest, compute_fill
from ab_screener.domain.execution.market_rules import floor_to_lot, slipped_price_micro
from ab_screener.domain.execution.models import (
    EXECUTION_MODEL_VERSION,
    FEE_VERSION,
    FillV2,
    Quote,
)
from ab_screener.domain.instrument import is_a_share_stock
from paper_trading.rules import InstrumentRule, default_rule

PORTFOLIO_MODEL_VERSION = "research-portfolio-v2.1.0"
_MICRO_PER_YUAN = Decimal(1000000)
_FEN_PER_AMOUNT_K_YUAN = Decimal(100000)


class PortfolioAccountingError(RuntimeError):
    """Fail-closed input or accounting error."""


@dataclass(frozen=True)
class PortfolioPolicy:
    version: str = PORTFOLIO_MODEL_VERSION
    initial_cash_fen: int = 100_000_000
    single_name_weight_bps: int = 1_000
    gross_exposure_bps: int = 8_000
    minimum_cash_bps: int = 1_000
    daily_new_buy_bps: int = 2_000
    participation_bps: int = 500
    cost_multiplier_bps: int = 10_000
    stock_lot_size: int = 100
    volume_unit: str = "hand"

    def __post_init__(self) -> None:
        if self.version != PORTFOLIO_MODEL_VERSION:
            raise PortfolioAccountingError(f"未知组合模型版本: {self.version}")
        if self.initial_cash_fen <= 0:
            raise PortfolioAccountingError("initial_cash_fen 必须为正整数")
        for name in (
            "single_name_weight_bps",
            "gross_exposure_bps",
            "minimum_cash_bps",
            "daily_new_buy_bps",
            "participation_bps",
            "cost_multiplier_bps",
        ):
            value = getattr(self, name)
            upper = 50_000 if name == "cost_multiplier_bps" else 10_000
            if not isinstance(value, int) or not 0 <= value <= upper:
                raise PortfolioAccountingError(f"{name} 必须为 0..{upper} 的整数")
        if self.cost_multiplier_bps <= 0:
            raise PortfolioAccountingError("cost_multiplier_bps 必须大于 0")
        if self.single_name_weight_bps > self.gross_exposure_bps:
            raise PortfolioAccountingError("单标的权重不能超过总仓位上限")
        if self.gross_exposure_bps + self.minimum_cash_bps > 10_000:
            raise PortfolioAccountingError("总仓位与最低现金之和不能超过 100%")
        if self.stock_lot_size <= 0:
            raise PortfolioAccountingError("stock_lot_size 必须为正整数")
        if self.volume_unit not in {"hand", "share"}:
            raise PortfolioAccountingError("volume_unit 只能是 hand 或 share")

    def fingerprint(self) -> str:
        payload = {key: getattr(self, key) for key in self.__dataclass_fields__}
        payload["execution_model_version"] = EXECUTION_MODEL_VERSION
        payload["fee_version"] = FEE_VERSION
        return hashlib.sha256(
            json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
        ).hexdigest()[:16]


@dataclass(frozen=True)
class PreparedPortfolioMarket:
    """Immutable-by-contract market index reused across a parameter grid."""

    bars: Mapping[tuple[str, str], Quote]
    calendar: tuple[str, ...]
    policy_fingerprint: str


@dataclass
class _Position:
    ts_code: str
    qty: int
    cost_basis_fen: int
    entry_date: str
    planned_exit_date: str
    planned_exit_price_micro: int
    exit_type: str
    last_close_micro: int
    realized_pnl_fen: int = 0


def load_portfolio_policy(path: str | Path) -> PortfolioPolicy:
    payload = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise PortfolioAccountingError("组合配置必须是对象")
    return PortfolioPolicy(**payload)


def resolved_stock_rules(
    codes: list[str],
    policy: PortfolioPolicy,
) -> dict[str, InstrumentRule]:
    """Resolve an explicit rule object per instrument; non-stock inputs fail."""
    result: dict[str, InstrumentRule] = {}
    for code in sorted(set(codes)):
        if not is_a_share_stock(code):
            raise PortfolioAccountingError(f"非 A 股股票不能进入首版组合研究: {code}")
        base = default_rule(code, "STOCK")
        result[code] = InstrumentRule(
            ts_code=code,
            inst_type="STOCK",
            commission_bps=base.commission_bps,
            min_commission_fen=base.min_commission_fen,
            sell_tax_bps=base.sell_tax_bps,
            other_fee_bps=base.other_fee_bps,
            slippage_bps=base.slippage_bps,
            lot_size=policy.stock_lot_size,
        )
    return result


def prepare_portfolio_market(
    market_data: pd.DataFrame,
    policy: PortfolioPolicy,
) -> PreparedPortfolioMarket:
    """Normalize OHLCV once so every grid combination sees identical quotes."""
    bars, calendar = _build_market_index(market_data, policy)
    return PreparedPortfolioMarket(
        bars=bars,
        calendar=tuple(calendar),
        policy_fingerprint=policy.fingerprint(),
    )


def simulate_portfolio(
    trades: list[dict[str, Any]],
    market_data: pd.DataFrame | PreparedPortfolioMarket,
    *,
    policy: PortfolioPolicy,
    rules: Mapping[str, InstrumentRule] | None = None,
    cancellation_checkpoint: Callable[[], None] | None = None,
    progress_callback: Callable[[int, int], None] | None = None,
) -> dict[str, Any]:
    """Run exact shared-account simulation over frozen candidate trades."""
    normalized = _normalize_trades(trades)
    if not normalized:
        return _empty_result(policy)
    if isinstance(market_data, PreparedPortfolioMarket):
        if market_data.policy_fingerprint != policy.fingerprint():
            raise PortfolioAccountingError("预处理行情与组合配置版本不一致")
        bars = market_data.bars
        calendar = list(market_data.calendar)
    else:
        prepared = prepare_portfolio_market(market_data, policy)
        bars = prepared.bars
        calendar = list(prepared.calendar)
    codes = sorted({row["ts_code"] for row in normalized})
    rule_map = dict(rules or resolved_stock_rules(codes, policy))
    missing_rules = sorted(set(codes) - set(rule_map))
    if missing_rules:
        raise PortfolioAccountingError(f"缺少 instrument 规则: {missing_rules[:5]}")

    entries: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in normalized:
        entries[row["entry_date"]].append(row)
    for dated_entries in entries.values():
        dated_entries.sort(key=lambda item: (item["signal_date"], item["ts_code"]))

    first_date = min(entries)
    relevant_calendar = [day for day in calendar if day >= first_date]
    if not relevant_calendar:
        raise PortfolioAccountingError("组合窗口内没有交易日")

    cash_fen = policy.initial_cash_fen
    positions: dict[str, _Position] = {}
    events: list[dict[str, Any]] = []
    equity_curve: list[dict[str, Any]] = []
    realized_pnls: list[int] = []
    fee_totals: Counter[str] = Counter()
    rejection_counts: Counter[str] = Counter()
    peak_fen = policy.initial_cash_fen
    min_cash_fen = cash_fen
    max_gross_bps = 0

    calendar_count = len(relevant_calendar)
    for calendar_index, trade_date in enumerate(relevant_calendar, start=1):
        if cancellation_checkpoint is not None:
            cancellation_checkpoint()
        if progress_callback is not None and (
            calendar_index == 1
            or calendar_index == calendar_count
            or calendar_index % 20 == 0
        ):
            progress_callback(calendar_index, calendar_count)
        day_start_equity = _equity_at_price(cash_fen, positions, bars, trade_date, price_field="open_micro")
        cash_fen = _process_exits(
            trade_date,
            cash_fen,
            positions,
            bars,
            rule_map,
            policy,
            events,
            realized_pnls,
            fee_totals,
            rejection_counts,
        )
        day_spend_fen = 0
        daily_entries: list[dict[str, Any]] = []
        for row in entries.get(trade_date, []):
            code = row["ts_code"]
            if code in positions:
                rejection_counts["DUPLICATE_ACTIVE_POSITION"] += 1
                events.append(
                    {
                        "event": "ENTRY_REJECTED",
                        "ts_code": code,
                        "trade_date": trade_date,
                        "filled": False,
                        "qty": 0,
                        "reason": "DUPLICATE_ACTIVE_POSITION",
                    }
                )
                continue
            daily_entries.append(row)
        for index, row in enumerate(daily_entries):
            code = row["ts_code"]
            bar = _require_bar(bars, code, trade_date)
            equity_open = _equity_at_price(cash_fen, positions, bars, trade_date, price_field="open_micro")
            gross_open = _market_value(positions, bars, trade_date, price_field="open_micro")
            reserve_fen = equity_open * policy.minimum_cash_bps // 10_000
            gross_room = max(0, equity_open * policy.gross_exposure_bps // 10_000 - gross_open)
            cash_room = max(0, cash_fen - reserve_fen)
            daily_room = max(
                0,
                day_start_equity * policy.daily_new_buy_bps // 10_000 - day_spend_fen,
            )
            available = min(gross_room, cash_room, daily_room)
            remaining = max(1, len(daily_entries) - index)
            single_cap = equity_open * policy.single_name_weight_bps // 10_000
            budget_fen = min(single_cap, available // remaining)
            fill = _buy_fill(code, trade_date, bar, rule_map[code], policy, budget_fen)
            if not fill.filled:
                rejection_counts[fill.reason] += 1
                events.append(_event_payload(fill, "ENTRY_REJECTED"))
                continue
            if fill.cash_delta_fen >= 0 or cash_fen + fill.cash_delta_fen < 0:
                raise PortfolioAccountingError("买入现金变化非法")
            cash_fen += fill.cash_delta_fen
            day_spend_fen += -fill.cash_delta_fen
            positions[code] = _Position(
                ts_code=code,
                qty=fill.qty,
                cost_basis_fen=-fill.cash_delta_fen,
                entry_date=trade_date,
                planned_exit_date=row["exit_date"],
                planned_exit_price_micro=row["exit_price_micro"],
                exit_type=row["exit_type"],
                last_close_micro=bar.close_micro,
            )
            _add_fees(fee_totals, fill)
            events.append(_event_payload(fill, "ENTRY_FILLED"))

        market_value_fen = _mark_positions(positions, bars, trade_date, events)
        equity_fen = cash_fen + market_value_fen
        if equity_fen < 0 or cash_fen < 0:
            raise PortfolioAccountingError("组合出现负现金或负权益")
        peak_fen = max(peak_fen, equity_fen)
        drawdown = Decimal(peak_fen - equity_fen) / Decimal(peak_fen)
        gross_bps = market_value_fen * 10_000 // equity_fen if equity_fen > 0 else 10_000
        max_gross_bps = max(max_gross_bps, gross_bps)
        min_cash_fen = min(min_cash_fen, cash_fen)
        equity_curve.append(
            {
                "trade_date": trade_date,
                "cash_fen": cash_fen,
                "market_value_fen": market_value_fen,
                "equity_fen": equity_fen,
                "gross_exposure_bps": gross_bps,
                "drawdown": _decimal_float(drawdown),
                "position_count": len(positions),
            }
        )

    final_equity = equity_curve[-1]["equity_fen"]
    positives = [value for value in realized_pnls if value > 0]
    negatives = [value for value in realized_pnls if value < 0]
    profit_factor = (
        Decimal(sum(positives)) / Decimal(abs(sum(negatives))) if positives and negatives else None
    )
    daily_returns = _daily_returns(equity_curve, policy.initial_cash_fen)
    result = {
        "portfolio_model_version": policy.version,
        "portfolio_config_hash": policy.fingerprint(),
        "portfolio_execution_model_version": EXECUTION_MODEL_VERSION,
        "portfolio_fee_version": FEE_VERSION,
        "portfolio_status": "PASS" if not positions else "INCOMPLETE_OPEN_POSITIONS",
        "portfolio_initial_equity_fen": policy.initial_cash_fen,
        "portfolio_final_equity_fen": final_equity,
        "portfolio_net_pnl_fen": final_equity - policy.initial_cash_fen,
        "portfolio_total_return": _decimal_float(
            Decimal(final_equity) / Decimal(policy.initial_cash_fen) - Decimal(1)
        ),
        "portfolio_max_drawdown": max((float(row["drawdown"]) for row in equity_curve), default=0.0),
        "portfolio_realized_profit_factor": (
            _decimal_float(profit_factor) if profit_factor is not None else None
        ),
        "portfolio_realized_win_rate": (
            round(len(positives) / len(realized_pnls), 6) if realized_pnls else None
        ),
        "portfolio_n_entries": sum(e["event"] == "ENTRY_FILLED" for e in events),
        "portfolio_n_exits": len(realized_pnls),
        "portfolio_rejections": int(sum(rejection_counts.values())),
        "portfolio_rejection_reasons": dict(sorted(rejection_counts.items())),
        "portfolio_open_positions": len(positions),
        "portfolio_min_cash_fen": min_cash_fen,
        "portfolio_max_gross_exposure_bps": max_gross_bps,
        "portfolio_commission_fen": fee_totals["commission_fen"],
        "portfolio_stamp_tax_fen": fee_totals["stamp_tax_fen"],
        "portfolio_other_fee_fen": fee_totals["other_fee_fen"],
        "portfolio_slippage_fen": fee_totals["slippage_fen"],
        "portfolio_daily_returns": daily_returns,
        "portfolio_equity_sha256": _equity_hash(equity_curve),
        "equity_curve": equity_curve,
        "events": events,
    }
    return result


def portfolio_gate_metrics(result: Mapping[str, Any]) -> dict[str, Any]:
    """Map portfolio facts onto the stable trusted-research net metric names."""
    pnl_fen = int(result.get("portfolio_net_pnl_fen") or 0)
    return {
        "net_n_trades": int(result.get("portfolio_n_exits") or 0),
        "net_unfilled": int(result.get("portfolio_rejections") or 0),
        "net_pnl": round(pnl_fen / 100, 2),
        "net_avg_return": result.get("portfolio_total_return"),
        "net_total_return": result.get("portfolio_total_return"),
        "net_win_rate": result.get("portfolio_realized_win_rate"),
        "net_profit_factor": result.get("portfolio_realized_profit_factor"),
        "net_max_drawdown": result.get("portfolio_max_drawdown"),
        "commission": round(int(result.get("portfolio_commission_fen") or 0) / 100, 2),
        "stamp_tax": round(int(result.get("portfolio_stamp_tax_fen") or 0) / 100, 2),
        "other_fee": round(int(result.get("portfolio_other_fee_fen") or 0) / 100, 2),
        "slippage_cost": round(int(result.get("portfolio_slippage_fen") or 0) / 100, 2),
        "portfolio_model_version": result.get("portfolio_model_version"),
        "portfolio_config_hash": result.get("portfolio_config_hash"),
        "portfolio_execution_model_version": result.get("portfolio_execution_model_version"),
        "portfolio_fee_version": result.get("portfolio_fee_version"),
        "portfolio_status": result.get("portfolio_status"),
        "portfolio_equity_sha256": result.get("portfolio_equity_sha256"),
        "portfolio_max_gross_exposure_bps": result.get("portfolio_max_gross_exposure_bps"),
        "portfolio_open_positions": result.get("portfolio_open_positions"),
    }


def _normalize_trades(trades: list[dict[str, Any]]) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    seen: set[tuple[str, str, str]] = set()
    for row in trades:
        if not row.get("cost", {}).get("filled"):
            continue
        code = str(row.get("ts_code") or "").strip().upper()
        signal_date = _date(row.get("date") or row.get("signal_date"))
        entry_date = _date(row.get("entry_date"))
        exit_date = _date(row.get("exit_date"))
        if not code or not signal_date or not entry_date or not exit_date:
            raise PortfolioAccountingError("成交候选缺少代码或信号/成交/退出日期")
        if not signal_date < entry_date < exit_date:
            raise PortfolioAccountingError(f"时间顺序非法: {code} {signal_date}/{entry_date}/{exit_date}")
        key = (code, entry_date, "")
        if key in seen:
            raise PortfolioAccountingError(f"重复成交候选: {key}")
        seen.add(key)
        exit_price_micro = _price_micro(row.get("exit_price"))
        if exit_price_micro <= 0:
            raise PortfolioAccountingError(f"退出参考价非法: {code} {exit_date}")
        result.append(
            {
                "ts_code": code,
                "signal_date": signal_date,
                "entry_date": entry_date,
                "exit_date": exit_date,
                "exit_price_micro": exit_price_micro,
                "exit_type": str(row.get("exit") or "time"),
            }
        )
    return sorted(result, key=lambda item: (item["entry_date"], item["ts_code"]))


def _build_market_index(
    market_data: pd.DataFrame,
    policy: PortfolioPolicy,
) -> tuple[dict[tuple[str, str], Quote], list[str]]:
    required = {"ts_code", "trade_date", "open", "high", "low", "close", "vol"}
    missing = required - set(market_data.columns)
    if missing:
        raise PortfolioAccountingError(f"行情缺字段: {sorted(missing)}")
    bars: dict[tuple[str, str], Quote] = {}
    for record in market_data.to_dict("records"):
        code = str(record["ts_code"]).strip().upper()
        trade_date = _date(record["trade_date"])
        key = (code, trade_date)
        if key in bars:
            raise PortfolioAccountingError(f"行情重复主键: {key}")
        volume = _int_decimal(record.get("vol"))
        if policy.volume_unit == "hand":
            volume *= 100
        amount_fen = _amount_fen(record.get("amount"))
        pre_close = record.get("pre_close")
        bars[key] = Quote(
            ts_code=code,
            trade_date=trade_date,
            open_micro=_price_micro(record.get("open")),
            high_micro=_price_micro(record.get("high")),
            low_micro=_price_micro(record.get("low")),
            close_micro=_price_micro(record.get("close")),
            vol=max(0, volume),
            amount_fen=max(0, amount_fen),
            pre_close_micro=(
                _price_micro(pre_close) if pre_close is not None and not pd.isna(pre_close) else None
            ),
            available_at=str(record.get("available_at") or ""),
        )
    calendar = sorted({date for _, date in bars})
    return bars, calendar


def _process_exits(
    trade_date: str,
    cash_fen: int,
    positions: dict[str, _Position],
    bars: Mapping[tuple[str, str], Quote],
    rules: Mapping[str, InstrumentRule],
    policy: PortfolioPolicy,
    events: list[dict[str, Any]],
    realized_pnls: list[int],
    fee_totals: Counter,
    rejection_counts: Counter[str],
) -> int:
    due = sorted(
        (position for position in positions.values() if position.planned_exit_date <= trade_date),
        key=lambda position: position.ts_code,
    )
    for position in due:
        actual = bars.get((position.ts_code, trade_date))
        if actual is None:
            rejection_counts["EXIT_NO_QUOTE"] += 1
            events.append(
                {
                    "event": "EXIT_RETRY",
                    "ts_code": position.ts_code,
                    "trade_date": trade_date,
                    "filled": False,
                    "qty": 0,
                    "reason": "NO_QUOTE",
                }
            )
            continue
        quote = actual
        if trade_date == position.planned_exit_date:
            quote = Quote(
                ts_code=actual.ts_code,
                trade_date=actual.trade_date,
                open_micro=position.planned_exit_price_micro,
                high_micro=actual.high_micro,
                low_micro=actual.low_micro,
                close_micro=actual.close_micro,
                vol=actual.vol,
                amount_fen=actual.amount_fen,
                pre_close_micro=actual.pre_close_micro,
                available_at=actual.available_at,
            )
        rule = rules[position.ts_code]
        fill = compute_fill(
            quote,
            FillRequest(
                ts_code=position.ts_code,
                side="SELL",
                trade_date=trade_date,
                input_hash=f"portfolio:{position.ts_code}:{position.entry_date}:{trade_date}:sell",
                participation_bps=policy.participation_bps,
                lot_size=rule.lot_size,
                position_qty=position.qty,
                requested_qty=position.qty,
                fees=portfolio_fee_params(rule, policy),
            ),
        )
        if not fill.filled:
            rejection_counts[f"EXIT_{fill.reason}"] += 1
            events.append(_event_payload(fill, "EXIT_RETRY"))
            continue
        old_qty = position.qty
        sold_cost = (
            position.cost_basis_fen if fill.qty == old_qty else position.cost_basis_fen * fill.qty // old_qty
        )
        position.qty -= fill.qty
        position.cost_basis_fen -= sold_cost
        cash_fen += fill.cash_delta_fen
        position.realized_pnl_fen += fill.cash_delta_fen - sold_cost
        _add_fees(fee_totals, fill)
        events.append({
            **_event_payload(fill, "EXIT_FILLED"),
            "entry_date": position.entry_date,
            "exit_type": position.exit_type,
            "allocated_cost_fen": sold_cost,
            "realized_pnl_fen": fill.cash_delta_fen - sold_cost,
        })
        if position.qty == 0:
            realized_pnls.append(position.realized_pnl_fen)
            del positions[position.ts_code]
    return cash_fen


def _buy_fill(
    code: str,
    trade_date: str,
    quote: Quote,
    rule: InstrumentRule,
    policy: PortfolioPolicy,
    budget_fen: int,
) -> FillV2:
    if budget_fen <= 0:
        return compute_fill(
            quote,
            FillRequest(
                ts_code=code,
                side="BUY",
                trade_date=trade_date,
                input_hash=f"portfolio:{code}:{trade_date}:zero-budget",
                participation_bps=policy.participation_bps,
                lot_size=rule.lot_size,
                cash_available_fen=0,
                requested_qty=rule.lot_size,
                fees=portfolio_fee_params(rule, policy),
            ),
        )
    if quote.open_micro <= 0:
        rough_qty = rule.lot_size
    else:
        buy_price = slipped_price_micro(
            quote.open_micro,
            "BUY",
            quote,
            _scaled_cost(rule.slippage_bps, policy.cost_multiplier_bps),
        )
        rough_qty = floor_to_lot(budget_fen * 10_000 // buy_price, rule.lot_size)
    return compute_fill(
        quote,
        FillRequest(
            ts_code=code,
            side="BUY",
            trade_date=trade_date,
            input_hash=f"portfolio:{code}:{trade_date}:buy",
            participation_bps=policy.participation_bps,
            lot_size=rule.lot_size,
            cash_available_fen=budget_fen,
            requested_qty=max(rough_qty, rule.lot_size),
            fees=portfolio_fee_params(rule, policy),
        ),
    )


def portfolio_fee_params(rule: InstrumentRule, policy: PortfolioPolicy) -> FeeParams:
    """Resolve the exact versioned fee/slippage assumptions for one policy."""
    return FeeParams(
        commission_bps=_scaled_cost(rule.commission_bps, policy.cost_multiplier_bps),
        commission_min_fen=_scaled_cost(rule.min_commission_fen, policy.cost_multiplier_bps),
        stamp_tax_bps=_scaled_cost(rule.sell_tax_bps, policy.cost_multiplier_bps),
        other_fee_bps=_scaled_cost(rule.other_fee_bps, policy.cost_multiplier_bps),
        slippage_bps=_scaled_cost(rule.slippage_bps, policy.cost_multiplier_bps),
    )


def _scaled_cost(value: int, multiplier_bps: int) -> int:
    return (int(value) * int(multiplier_bps) + 5_000) // 10_000


def _event_payload(fill: FillV2, event: str) -> dict[str, Any]:
    return {"event": event, **fill.to_dict()}


def _add_fees(totals: Counter, fill: FillV2) -> None:
    for key, value in fill.fees.to_dict().items():
        totals[key] += value


def _market_value(
    positions: Mapping[str, _Position],
    bars: Mapping[tuple[str, str], Quote],
    trade_date: str,
    *,
    price_field: str,
) -> int:
    total = 0
    for code, position in positions.items():
        quote = bars.get((code, trade_date))
        price_micro = int(getattr(quote, price_field)) if quote is not None else position.last_close_micro
        total += price_micro * position.qty // 10_000
    return total


def _equity_at_price(
    cash_fen: int,
    positions: Mapping[str, _Position],
    bars: Mapping[tuple[str, str], Quote],
    trade_date: str,
    *,
    price_field: str,
) -> int:
    return cash_fen + _market_value(positions, bars, trade_date, price_field=price_field)


def _mark_positions(
    positions: Mapping[str, _Position],
    bars: Mapping[tuple[str, str], Quote],
    trade_date: str,
    events: list[dict[str, Any]],
) -> int:
    total = 0
    for code, position in positions.items():
        quote = bars.get((code, trade_date))
        if quote is not None:
            position.last_close_micro = quote.close_micro
        else:
            events.append(
                {
                    "event": "MARK_CARRY_FORWARD",
                    "ts_code": code,
                    "trade_date": trade_date,
                    "price_micro": position.last_close_micro,
                    "reason": "NO_QUOTE",
                }
            )
        total += position.last_close_micro * position.qty // 10_000
    return total


def _require_bar(
    bars: Mapping[tuple[str, str], Quote],
    code: str,
    trade_date: str,
) -> Quote:
    quote = bars.get((code, trade_date))
    if quote is None:
        raise PortfolioAccountingError(f"持仓或成交缺少当日估值行情: {code} {trade_date}")
    return quote


def _daily_returns(equity_curve: list[dict[str, Any]], initial_equity_fen: int) -> list[float]:
    result: list[float] = []
    previous = initial_equity_fen
    for row in equity_curve:
        equity = int(row["equity_fen"])
        if previous > 0:
            result.append(_decimal_float(Decimal(equity) / Decimal(previous) - Decimal(1)))
        previous = equity
    return result


def _equity_hash(equity_curve: list[dict[str, Any]]) -> str:
    payload = json.dumps(equity_curve, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _date(value: Any) -> str:
    digits = "".join(ch for ch in str(value or "") if ch.isdigit())
    return digits[:8] if len(digits) >= 8 else ""


def _price_micro(value: Any) -> int:
    if value is None or pd.isna(value):
        return 0
    return int((Decimal(str(value)) * _MICRO_PER_YUAN).quantize(Decimal(1), rounding=ROUND_HALF_UP))


def _int_decimal(value: Any) -> int:
    if value is None or pd.isna(value):
        return 0
    return int(Decimal(str(value)))


def _amount_fen(value: Any) -> int:
    if value is None or pd.isna(value):
        return 0
    return int((Decimal(str(value)) * _FEN_PER_AMOUNT_K_YUAN).quantize(Decimal(1), rounding=ROUND_HALF_UP))


def _decimal_float(value: Decimal) -> float:
    return float(value.quantize(Decimal("0.00000001"), rounding=ROUND_HALF_UP))


def _empty_result(policy: PortfolioPolicy) -> dict[str, Any]:
    return {
        "portfolio_model_version": policy.version,
        "portfolio_config_hash": policy.fingerprint(),
        "portfolio_execution_model_version": EXECUTION_MODEL_VERSION,
        "portfolio_fee_version": FEE_VERSION,
        "portfolio_status": "EMPTY",
        "portfolio_initial_equity_fen": policy.initial_cash_fen,
        "portfolio_final_equity_fen": policy.initial_cash_fen,
        "portfolio_net_pnl_fen": 0,
        "portfolio_total_return": 0.0,
        "portfolio_max_drawdown": 0.0,
        "portfolio_realized_profit_factor": None,
        "portfolio_realized_win_rate": None,
        "portfolio_n_entries": 0,
        "portfolio_n_exits": 0,
        "portfolio_rejections": 0,
        "portfolio_rejection_reasons": {},
        "portfolio_open_positions": 0,
        "portfolio_min_cash_fen": policy.initial_cash_fen,
        "portfolio_max_gross_exposure_bps": 0,
        "portfolio_commission_fen": 0,
        "portfolio_stamp_tax_fen": 0,
        "portfolio_other_fee_fen": 0,
        "portfolio_slippage_fen": 0,
        "portfolio_daily_returns": [],
        "portfolio_equity_sha256": _equity_hash([]),
        "equity_curve": [],
        "events": [],
    }
